Dockerfile.dbg
Dockerfile.in
Makefile
README.md
cmd/stash-redis/main.go
go.mod
pkg/backup.go
pkg/restore.go
pkg/root.go
pkg/util.go

Signed-off-by: hossainemruz <emruz@appscode.com>

Global replace Redis with Etcd

---

go.mod
go.sum
vendor/modules.txt

[cherry-pick] Fix jwt-go security vulnerability (#7)

---

go.mod
go.sum
vendor/modules.txt

ProductLine: Stash
Release: v2021.10.11

Prepare for release v2021.10.11

---

go.mod
go.sum
vendor/go.bytebuilders.dev/license-verifier/Makefile
vendor/go.bytebuilders.dev/license-verifier/info/lib.go
vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.mod
vendor/go.bytebuilders.dev/license-verifier/kubernetes/lib.go
vendor/go.bytebuilders.dev/license-verifier/lib.go
vendor/modules.txt

[cherry-pick] Update dependencies (#14)

---

go.mod
go.sum
vendor/go.bytebuilders.dev/license-verifier/info/lib.go
vendor/go.bytebuilders.dev/license-verifier/kubernetes/go.mod
vendor/go.bytebuilders.dev/license-verifier/kubernetes/lib.go
vendor/go.bytebuilders.dev/license-verifier/lib.go
vendor/modules.txt

[cherry-pick] Fix SiteInfo publishing (#16)

---

pkg/backup.go
pkg/rbac.go
pkg/restore.go
pkg/restore_member.go
pkg/root.go
pkg/util.go

[cherry-pick] make fmt (#28)

---

.github/workflows/ci.yml
Makefile

[cherry-pick] Use Go 1.18 (#30)

---

Makefile
go.mod
go.sum
vendor/kmodules.xyz/client-go/api/v1/timeofday.go
vendor/kmodules.xyz/client-go/meta/incluster.go
vendor/modules.txt

[cherry-pick] Use restic 0.13.1 (#37)

---

pkg/backup.go
pkg/restore.go

Signed-off-by: piyush1146115 <piyush@appscode.com>

Make sure to fail the backup/restore sessions if license check fails.

---

pkg/backup.go
pkg/restore.go

* Make sure to fail the backup/restore sessions if license check fails.
Signed-off-by: piyush1146115 <piyush@appscode.com>
* Refactor implementation.
Signed-off-by: piyush1146115 <piyush@appscode.com>

[cherry-pick] Make sure to fail the backup/restore sessions if license check fails. (#45)

---

go.mod

Use Go 1.18 (#32)

---

Makefile

Signed-off-by: Tamal Saha <tamal@appscode.com>

[cherry-pick] Use restic 0.14.0 (#55)

---

Makefile

Signed-off-by: Tamal Saha <tamal@appscode.com>

[cherry-pick] Revert to restic 0.13.1 (#57)

---

.github/workflows/cherry-pick.yml
.github/workflows/ci.yml
.github/workflows/release-tracker.yml
.github/workflows/release.yml

[cherry-pick] Run GH actions on ubuntu-20.04 (#61)

---

.github/workflows/ci.yml
Makefile
go.mod
go.sum
vendor/golang.org/x/crypto/AUTHORS
vendor/golang.org/x/crypto/CONTRIBUTORS
vendor/golang.org/x/crypto/pkcs12/crypto.go
vendor/golang.org/x/crypto/pkcs12/internal/rc2/rc2.go
vendor/modules.txt

Signed-off-by: Tamal Saha <tamal@appscode.com>

[cherry-pick] Update workflows (Go 1.20, k8s 1.26) (#69)

---

go.mod
go.sum
vendor/modules.txt
vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go

ProductLine: Stash
Release: v2023.03.13
Release-tracker: https://github.com/stashed/CHANGELOG/pull/63

Prepare for release 3.5.0-v10

---

Dockerfile.in

Signed-off-by: Tamal Saha <tamal@appscode.com>

[cherry-pick] Use numeric uid in Dockerfile (#75)

---

go.mod
go.sum
vendor/modules.txt
vendor/stash.appscode.dev/apimachinery/apis/repositories/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/stash/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/stash/v1beta1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/apis/ui/v1alpha1/openapi_generated.go
vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go
vendor/stash.appscode.dev/apimachinery/pkg/restic/restore.go

ProductLine: Stash
Release: v2023.04.30
Release-tracker: https://github.com/stashed/CHANGELOG/pull/65

Prepare for release 3.5.0-v12

---

.github/workflows/cherry-pick.yml
.github/workflows/ci.yml
.github/workflows/release-tracker.yml
.github/workflows/release.yml
Makefile

Use Go 1.23 (#97)

---

Dockerfile.dbg
Dockerfile.in

[cherry-pick] Use debian:12 base image (#104)

---

Makefile
go.mod
go.sum
vendor/modules.txt
vendor/stash.appscode.dev/apimachinery/pkg/restic/commands.go
vendor/stash.appscode.dev/apimachinery/pkg/restic/config.go
vendor/stash.appscode.dev/apimachinery/pkg/restic/migrate.go

Signed-off-by: Md. Ishtiaq Islam <ishtiaq@appscode.com>

[cherry-pick] Update restic version (#112)

---

.github/workflows/ci.yml
.github/workflows/release.yml
pkg/util.go

[cherry-pick] Disable image caching in setup-qemu action (#114)

---

.github/workflows/ci.yml
Makefile

[cherry-pick] Use Go 1.24 (#118)
